<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="5" skipped="2" tests="8" time="2301.787" timestamp="2025-08-12T20:12:24.227319" hostname="MacBook-Air-3.local"><testcase classname="tests.auth.test_biometric_authentication.TestBiometricAuthentication" name="test_biometric_settings_visibility_when_available" time="195.714"><failure message="selenium.common.exceptions.NoSuchElementException: Message: Element not found after 10 scrolls: ('xpath', &quot;//*[contains(@text, 'Privacy &amp; Security')]&quot;); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception">tests/auth/test_biometric_authentication.py:115: in test_biometric_settings_visibility_when_available
    has_biometric_toggle = self.settings_page.navigate_to_biometric_settings()
tests/auth/test_biometric_authentication.py:40: in navigate_to_biometric_settings
    self.scroll_to_element(self.PRIVACY_SECURITY_SECTION)
tests/common/page_objects/base_page.py:173: in scroll_to_element
    raise NoSuchElementException(f"Element not found after {max_scrolls} scrolls: {locator}")
E   selenium.common.exceptions.NoSuchElementException: Message: Element not found after 10 scrolls: ('xpath', "//*[contains(@text, 'Privacy &amp; Security')]"); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception</failure></testcase><testcase classname="tests.auth.test_biometric_authentication.TestBiometricAuthentication" name="test_enable_biometric_authentication" time="189.927"><failure message="selenium.common.exceptions.NoSuchElementException: Message: Element not found after 10 scrolls: ('xpath', &quot;//*[contains(@text, 'Privacy &amp; Security')]&quot;); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception">tests/auth/test_biometric_authentication.py:127: in test_enable_biometric_authentication
    has_biometric_toggle = self.settings_page.navigate_to_biometric_settings()
tests/auth/test_biometric_authentication.py:40: in navigate_to_biometric_settings
    self.scroll_to_element(self.PRIVACY_SECURITY_SECTION)
tests/common/page_objects/base_page.py:173: in scroll_to_element
    raise NoSuchElementException(f"Element not found after {max_scrolls} scrolls: {locator}")
E   selenium.common.exceptions.NoSuchElementException: Message: Element not found after 10 scrolls: ('xpath', "//*[contains(@text, 'Privacy &amp; Security')]"); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception</failure></testcase><testcase classname="tests.auth.test_biometric_authentication.TestBiometricAuthentication" name="test_disable_biometric_authentication" time="185.693"><failure message="selenium.common.exceptions.NoSuchElementException: Message: Element not found after 10 scrolls: ('xpath', &quot;//*[contains(@text, 'Privacy &amp; Security')]&quot;); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception">tests/auth/test_biometric_authentication.py:157: in test_disable_biometric_authentication
    has_biometric_toggle = self.settings_page.navigate_to_biometric_settings()
tests/auth/test_biometric_authentication.py:40: in navigate_to_biometric_settings
    self.scroll_to_element(self.PRIVACY_SECURITY_SECTION)
tests/common/page_objects/base_page.py:173: in scroll_to_element
    raise NoSuchElementException(f"Element not found after {max_scrolls} scrolls: {locator}")
E   selenium.common.exceptions.NoSuchElementException: Message: Element not found after 10 scrolls: ('xpath', "//*[contains(@text, 'Privacy &amp; Security')]"); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception</failure></testcase><testcase classname="tests.auth.test_biometric_authentication.TestBiometricAuthentication" name="test_biometric_unlock_button_visibility" time="78.793"><skipped type="pytest.skip" message="Biometric unlock not available - either not supported or not enabled">/Users/kaleewou/smor-ting/smor_ting_mobile/appium/tests/auth/test_biometric_authentication.py:196: Biometric unlock not available - either not supported or not enabled</skipped></testcase><testcase classname="tests.auth.test_biometric_authentication.TestBiometricAuthentication" name="test_biometric_unlock_flow" time="73.120"><skipped type="pytest.skip" message="Biometric unlock not available">/Users/kaleewou/smor-ting/smor_ting_mobile/appium/tests/auth/test_biometric_authentication.py:205: Biometric unlock not available</skipped></testcase><testcase classname="tests.auth.test_biometric_authentication.TestBiometricAuthentication" name="test_biometric_unlock_with_no_enrolled_biometrics" time="74.235" /><testcase classname="tests.auth.test_biometric_authentication.TestBiometricAuthentication" name="test_biometric_settings_persistence" time="181.167"><failure message="selenium.common.exceptions.NoSuchElementException: Message: Element not found after 10 scrolls: ('xpath', &quot;//*[contains(@text, 'Privacy &amp; Security')]&quot;); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception">tests/auth/test_biometric_authentication.py:257: in test_biometric_settings_persistence
    has_biometric_toggle = self.settings_page.navigate_to_biometric_settings()
tests/auth/test_biometric_authentication.py:40: in navigate_to_biometric_settings
    self.scroll_to_element(self.PRIVACY_SECURITY_SECTION)
tests/common/page_objects/base_page.py:173: in scroll_to_element
    raise NoSuchElementException(f"Element not found after {max_scrolls} scrolls: {locator}")
E   selenium.common.exceptions.NoSuchElementException: Message: Element not found after 10 scrolls: ('xpath', "//*[contains(@text, 'Privacy &amp; Security')]"); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception</failure></testcase><testcase classname="tests.auth.test_forgot_password" name="test_forgot_password_flow" time="80.771"><failure message="selenium.common.exceptions.InvalidSessionIdException: Message: A session is either terminated or not started&#10;Stacktrace:&#10;NoSuchDriverError: A session is either terminated or not started&#10;    at asyncHandler (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:311:15)&#10;    at /Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:514:15&#10;    at Layer.handle [as handle_request] (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)&#10;    at next (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/express/lib/router/route.js:149:13)&#10;    at Route.dispatch (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/express/lib/router/route.js:119:3)&#10;    at Layer.handle [as handle_request] (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)&#10;    at /Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:15&#10;    at param (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/express/lib/router/index.js:365:14)&#10;    at param (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/express/lib/router/index.js:376:14)&#10;    at Function.process_params (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/express/lib/router/index.js:421:3)&#10;    at next (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/express/lib/router/index.js:280:10)&#10;    at logger (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/morgan/index.js:144:5)&#10;    at Layer.handle [as handle_request] (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)&#10;    at trim_prefix (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/express/lib/router/index.js:328:13)&#10;    at /Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/express/lib/router/index.js:286:9&#10;    at Function.process_params (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/express/lib/router/index.js:346:12)&#10;    at next (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/express/lib/router/index.js:280:10)&#10;    at /Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/body-parser/lib/read.js:137:5&#10;    at AsyncResource.runInAsyncScope (node:async_hooks:214:14)&#10;    at invokeCallback (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/raw-body/index.js:238:16)&#10;    at done (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/raw-body/index.js:227:7)&#10;    at IncomingMessage.onEnd (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/raw-body/index.js:287:7)&#10;    at IncomingMessage.emit (node:events:518:28)&#10;    at endReadableNT (node:internal/streams/readable:1698:12)&#10;    at processTicksAndRejections (node:internal/process/task_queues:90:21)">tests/auth/test_forgot_password.py:17: in test_forgot_password_flow
    forgot.fill_email('user@example.com')
tests/common/page_objects/auth_pages.py:646: in fill_email
    fields = self.driver.find_elements(AppiumBy.CLASS_NAME, "android.widget.EditText")
../../../Library/Python/3.9/lib/python/site-packages/appium/webdriver/webdriver.py:420: in find_elements
    return self.execute(RemoteCommand.FIND_ELEMENTS, {'using': by, 'value': value})['value'] or []
../../../Library/Python/3.9/lib/python/site-packages/selenium/webdriver/remote/webdriver.py:347: in execute
    self.error_handler.check_response(response)
../../../Library/Python/3.9/lib/python/site-packages/appium/webdriver/errorhandler.py:125: in check_response
    raise exception_class(msg=message, stacktrace=format_stacktrace(stacktrace))
E   selenium.common.exceptions.InvalidSessionIdException: Message: A session is either terminated or not started
E   Stacktrace:
E   NoSuchDriverError: A session is either terminated or not started
E       at asyncHandler (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:311:15)
E       at /Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:514:15
E       at Layer.handle [as handle_request] (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
E       at next (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/express/lib/router/route.js:149:13)
E       at Route.dispatch (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/express/lib/router/route.js:119:3)
E       at Layer.handle [as handle_request] (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
E       at /Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:15
E       at param (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/express/lib/router/index.js:365:14)
E       at param (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/express/lib/router/index.js:376:14)
E       at Function.process_params (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/express/lib/router/index.js:421:3)
E       at next (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/express/lib/router/index.js:280:10)
E       at logger (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/morgan/index.js:144:5)
E       at Layer.handle [as handle_request] (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
E       at trim_prefix (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/express/lib/router/index.js:328:13)
E       at /Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/express/lib/router/index.js:286:9
E       at Function.process_params (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/express/lib/router/index.js:346:12)
E       at next (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/express/lib/router/index.js:280:10)
E       at /Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/body-parser/lib/read.js:137:5
E       at AsyncResource.runInAsyncScope (node:async_hooks:214:14)
E       at invokeCallback (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/raw-body/index.js:238:16)
E       at done (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/raw-body/index.js:227:7)
E       at IncomingMessage.onEnd (/Users/kaleewou/.npm-global/lib/node_modules/appium/node_modules/raw-body/index.js:287:7)
E       at IncomingMessage.emit (node:events:518:28)
E       at endReadableNT (node:internal/streams/readable:1698:12)
E       at processTicksAndRejections (node:internal/process/task_queues:90:21)</failure></testcase></testsuite></testsuites>